// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6TgMbZBjNMFMgpde9XDy_f--LY7M-fY',
    appId: '1:250845491438:web:ce63c9576c774d055c83ff',
    messagingSenderId: '250845491438',
    projectId: 'snaplearn-bdd69',
    authDomain: 'snaplearn-bdd69.firebaseapp.com',
    storageBucket: 'snaplearn-bdd69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuYSnOr-KBgCakZpea-cAproHyUsl3p6U',
    appId: '1:250845491438:android:a47e38c52c8f7ce65c83ff',
    messagingSenderId: '250845491438',
    projectId: 'snaplearn-bdd69',
    storageBucket: 'snaplearn-bdd69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJaEcm8_oCm3h8s0qGFvrmktMCiTaVqe0',
    appId: '1:250845491438:ios:06714263a8b89b2e5c83ff',
    messagingSenderId: '250845491438',
    projectId: 'snaplearn-bdd69',
    storageBucket: 'snaplearn-bdd69.firebasestorage.app',
    iosBundleId: 'com.example.textApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJaEcm8_oCm3h8s0qGFvrmktMCiTaVqe0',
    appId: '1:250845491438:ios:06714263a8b89b2e5c83ff',
    messagingSenderId: '250845491438',
    projectId: 'snaplearn-bdd69',
    storageBucket: 'snaplearn-bdd69.firebasestorage.app',
    iosBundleId: 'com.example.textApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6TgMbZBjNMFMgpde9XDy_f--LY7M-fY',
    appId: '1:250845491438:web:6109cef2abc5e4b05c83ff',
    messagingSenderId: '250845491438',
    projectId: 'snaplearn-bdd69',
    authDomain: 'snaplearn-bdd69.firebaseapp.com',
    storageBucket: 'snaplearn-bdd69.firebasestorage.app',
  );
}
